<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationIcon>MeshWaveIcon128.ico</ApplicationIcon>
    <AssemblyName>MeshWave</AssemblyName>
    <AssemblyTitle>MeshWave</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\mesh_background.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\MeshBackground.jpg" />
    <Resource Include="MeshWaveIcon128.ico" />
    <Resource Include="Assets\MeshWaveIcon128.png" />
    <Resource Include="Assets\LargeSplashLogo.jpg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../MeshWave.Common.Core/MeshWave.Common.Core.csproj" />
    <ProjectReference Include="../MeshWave.LibraryManager/MeshWave.LibraryManager.csproj" />
    <ProjectReference Include="../MeshWave.Synchronizer/MeshWave.Synchronizer.csproj" />
    <ProjectReference Include="../MeshWave.TestUtilities/MeshWave.TestUtilities.csproj" />
    <ProjectReference Include="../MeshWave.Wpf.OpenMpt/MeshWave.Wpf.OpenMpt.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AsyncAwaitBestPractices.MVVM" Version="10.0.0" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="OpenTK.GLWpfControl" Version="4.3.6" />
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="NLog" Version="*" />
  </ItemGroup>

</Project>
