using System.Text.Json;

namespace MeshWave.LibraryManager;

/// <summary>
/// Provides lookups for album and track names from their hash IDs.
/// Uses the mapping files generated by LocalLibraryManager.
/// </summary>
public class MetadataLookupRepository
{
    private readonly string _localMusicBaseFolder;

    public MetadataLookupRepository(string localMusicBaseFolder)
    {
        _localMusicBaseFolder = localMusicBaseFolder;
    }

    public string ResolveAlbumName(string artist, string albumId)
    {
        var artistFolder = Path.Combine(_localMusicBaseFolder, artist);
        var mapPath = Path.Combine(artistFolder, "album_map.json");
        var map = LoadMap(mapPath);
        return map.TryGetValue(albumId, out var name) ? name : albumId;
    }

    public (string title, int version) ResolveTrackInfo(string artist, string album, string trackId)
    {
        var albumFolder = Path.Combine(_localMusicBaseFolder, artist, album);
        var mapPath = Path.Combine(albumFolder, "track_map.json");
        var map = LoadMap(mapPath);
        if (map.TryGetValue(trackId, out var info))
        {
            var parts = info.Split('|');
            var title = parts[0];
            var version = parts.Length > 1 && int.TryParse(parts[1], out var v) ? v : 1;
            return (title, version);
        }
        return (trackId, 1);
    }

    private static Dictionary<string, string> LoadMap(string path)
    {
        if (!File.Exists(path)) return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        try
        {
            var json = File.ReadAllText(path);
            return JsonSerializer.Deserialize<Dictionary<string, string>>(json) ?? new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        }
        catch { return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase); }
    }
}
